In [1]:
import numpy as np
import qmt

#### Vorwärtskinematik mit Quaternionen

In [2]:
''' link: torso --> left_hip_roll ''' # Joint: hip_abduction_left
v01 = np.array([-0.001, 0.091, 0])
angle1 = -np.pi / 2
axis1 = np.array([0, 1, 0])
angle2 = -0.3752458
axis2 = np.array([0, 0, 1])
q01_1 = qmt.quatFromAngleAxis(angle1, axis1)
q01_2 = qmt.quatFromAngleAxis(angle2, axis2)
q01 = qmt.qmult(q01_1, q01_2)
print(q01)
#qmt.rotate(q01, v01)

print(qmt.quatFromEulerAngles(np.array([0, angle1, angle2]), axes='xyz')) #### ros macht xyz anscheinend

"""
Werte korrekt
Achtung: ROS macht xyzw, qmt ist wxyz !!!
hier stimmt was gehörig nicht in ros ist eine rotation mehr aber werte trotzdem richtig
"""

[ 0.69469734  0.13189241 -0.69469734 -0.13189241]
[ 0.69469734  0.13189241 -0.69469734 -0.13189241]


'\nWerte korrekt\nAchtung: ROS macht xyzw, qmt ist wxyz !!!\nhier stimmt was gehörig nicht in ros ist eine rotation mehr aber werte trotzdem richtig\n'

In [24]:
''' left_hip_roll --> left_hip_yaw  ''' # joint: hip_rotation_left
v12 = np.array([-0.0505, 0, 0.044])     # Vector / Translation
angle = -np.pi / 2                       # Winkel um den gedreht wird
axis = np.array([0, 1, 0])              # Achse um die gedreht wird
q12 = qmt.quatFromAngleAxis(angle, axis)    # erzeugt Rotationsquaternion
#qmt.rotate(q12, v12)   # rotieren
print('w x y z')
print(q12)
""" 
Werte korrekt
Achtung: ROS macht xyzw, qmt ist wxyz
"""

qmt.qmult(q01, q12)


w x y z
[ 0.70710678 -0.         -0.70710678 -0.        ]


array([ 1.11022302e-16, -1.38777878e-17, -9.82450397e-01, -1.86524041e-01])

In [52]:
def get_quat_23(q):
    var1 = 0.270598
    var2 = 2
    var3 = np.cos(q/var2)
    var4 = -0.653281
    var5 = np.sin(q/var2)
    var6 = 0.653281
    var7 = var1

    return np.array(
        [
            
            ((var7*var3) + (var6*var5)),
            ((var1*var3) - (var4*var5)),
            ((var1*var5) + (var4*var3)),
            ((var3*var6) - (var7*var5)),
            
        ]
    )

In [58]:
''' left_hip_yaw --> left_hip_pitch ''' # joint: hip_flexion_left
v23 = np.array([0, 0.004, 0.068]) 
angle1 = -np.pi / 2
axis1 = np.array([1, 0, 0])
angle2 = -np.pi / 4
axis2 = np.array([0, 1, 0])
angle3 = np.pi
axis3 = np.array([0, 0, 1])

q23_1 = qmt.quatFromAngleAxis(angle1, axis1)
q23_2 = qmt.quatFromAngleAxis(angle2, axis2)
q23_3 = qmt.quatFromAngleAxis(angle3, axis3)

q23 = qmt.qmult(q23_1, q23_2)
q23 = qmt.qmult(q23, q23_3)
print('w x y z')
print(q23)

angles = np.array([angle1, angle2, angle3])
print(qmt.quatFromEulerAngles(angles, axes='xyz'))
"""
In ROS left_hip_yaw --> left_hip_pitch
beides falsch, nochmal in Ruhe anschauen
Achtung: ROS macht xyzw, qmt ist wxyz
"""
q23_fake = np.array([0.271, 0.271, -0.653, 0.653]) / np.linalg.norm(np.array([0.271, 0.271, -0.653, 0.653])) # meins funktioniert nicht deswegen einfach von ROS geklaut
print(qmt.qrel(q23_fake, qmt.quatFromEulerAngles(angles, axes='zyx')))
q23 = get_quat_23(0)
q23

w x y z
[-0.27059805 -0.27059805  0.65328148  0.65328148]
[-0.27059805 -0.27059805  0.65328148  0.65328148]
[ 0.85379277 -0.146207   -0.35365254 -0.35297493]


array([ 0.270598,  0.270598, -0.653281,  0.653281])

In [5]:
''' left_hip_pitch --> left_knee ''' # joint: knee_joint_left
v34 = np.array([0.12, 0, 0.0045])
angle = -np.pi / 2
axis = np.array([0, 0, 1])
q34 = qmt.quatFromAngleAxis(angle, axis)
#qmt.rotate(q34, v34)
print('w x y z')
print(q34)
"""

Werte korrekt
Achtung: ROS macht xyzw, qmt ist wxyz
"""

w x y z
[ 0.70710678 -0.         -0.         -0.70710678]


'\n\nWerte korrekt\nAchtung: ROS macht xyzw, qmt ist wxyz\n'

In [6]:
''' left_knee --> left_shin ''' # knee_to_shin_left
v45 = np.array([0.060677, 0.047406, 0])
angle = 0
axis = np.array([0, 0, 1])
q45 = qmt.quatFromAngleAxis(angle, axis)
#qmt.rotate(q45, v45)
print('w x y z')
print(q45)
"""

Werte korrekt
Achtung: ROS macht xyzw, qmt ist wxyz
"""

w x y z
[1. 0. 0. 0.]


'\n\nWerte korrekt\nAchtung: ROS macht xyzw, qmt ist wxyz\n'

In [7]:
''' left_shin --> left_tarsus ''' # joint: shin_to_tarsus_left
v56 = np.array([0.434759, 0.02, 0])
angle = 1.7976891
axis = np.array([0, 0, 1])
q56 = qmt.quatFromAngleAxis(angle, axis)
#qmt.rotate(q56, v56)
print('w x y z')
print(q56)
"""

Werte korrekt
Achtung: ROS macht xyzw, qmt ist wxyz
"""

w x y z
[0.62251465 0.         0.         0.78260815]


'\n\nWerte korrekt\nAchtung: ROS macht xyzw, qmt ist wxyz\n'

In [8]:
''' left_tarsus --> left_heel_spring ''' # joint: tarsus_to_heel_spring_left
# kann ignoriert werden

' left_tarsus --> left_heel_spring '

In [9]:
''' left_tarsus --> left_toe_pitch ''' # joint: toe_pitch_joint_left
v67 = np.array([0.408, -0.04, 0])
angle = 1.1956
axis = np.array([0, 0, 1])
q67 = qmt.quatFromAngleAxis(angle, axis)
#qmt.rotate(q67, v67)
print('w x y z')
print(q67)
"""

Werte korrekt
Achtung: ROS macht xyzw, qmt ist wxyz
"""

w x y z
[0.82657583 0.         0.         0.56282537]


'\n\nWerte korrekt\nAchtung: ROS macht xyzw, qmt ist wxyz\n'

In [10]:
''' left_toe_pitch --> left_toe_roll ''' # joint: toe_roll_joint_left
v78 = np.array([0, 0, 0])
angle = np.pi / 2
axis = np.array([0, 1, 0])
q78 = qmt.quatFromAngleAxis(angle, axis)
#qmt.rotate(q78, v78)
print('w x y z')
print(q78)
"""

Werte korrekt
Achtung: ROS macht xyzw, qmt ist wxyz
"""

w x y z
[0.70710678 0.         0.70710678 0.        ]


'\n\nWerte korrekt\nAchtung: ROS macht xyzw, qmt ist wxyz\n'

In [27]:
''' left_toe_roll --> left_toe ''' # joint: toe_joint_left ## fixed
v89 = np.array([0, -0.05456, -0.0315])
angle1 = -1.0471975
axis1 = np.array([0, 1, 0])
angle2 = -np.pi / 2
axis2 = np.array([0, 0, 1])
q89_1 = qmt.quatFromAngleAxis(angle1, axis1)
q89_2 = qmt.quatFromAngleAxis(angle2, axis2)
q89 = qmt.qmult(q89_2, q89_1)
#qmt.rotate(q89, v89)
print('w x y z')
print(q89)
"""

Werte korrekt korrekt wenn man die mult. tauscht. Muss ich mir nochmal genau angucken wie es richtig gehört.
Ich habe mir die Frames angeschaut, es wird erst um z gedreht dann um y. Wobei es handelt sich um die neue y. 
Ich dachte es wäre nicht Euler?? (Vlt Erkenntnis für andere Transformationen.)
Neuste Erkenntnis. Es wird Euler um z dann y gedreht ist das gleiche wie raumfeste Achsen erst um y dann um z.
"""

w x y z
[ 0.61237244 -0.35355337 -0.35355337 -0.61237244]


'\n\nWerte korrekt korrekt wenn man die mult. tauscht. Muss ich mir nochmal genau angucken wie es richtig gehört.\nIch habe mir die Frames angeschaut, es wird erst um z gedreht dann um y. Wobei es handelt sich um die neue y. \nIch dachte es wäre nicht Euler?? (Vlt Erkenntnis für andere Transformationen.)\nNeuste Erkenntnis. Es wird Euler um z dann y gedreht ist das gleiche wie raumfeste Achsen erst um y dann um z.\n'


0 = torso  
1 = left_hip_roll  
2 = left_hip_yaw  
3 = left_hip_pitch  
4 = left_knee  
5 = left_shin  
6 = left_tarsus  
7 = left_toe_pitch  
8 = left_toe_roll  
9 = left_toe

#### Let's try

In [76]:
print('w x y z')
q02 = qmt.qmult(q01, q12) # torso --> left_hip_yaw
print('torso --> left_hip_yaw:           ', q02) # Werte sind negiert aber Transformation ist die selbe nur in die andere Richtung gedreht --> Werte korrekt :)

q24 = qmt.qmult(q23, q34) # left_hip_yaw --> left_knee
print('left_hip_yaw --> left_knee:       ', q24) # Werte korrekt :)

q46 = qmt.qmult(q45, q56) # left_knee --> left_tarsus
print('left_knee --> left_tarsus:        ', q46) # Werte korrekt

q68 = qmt.qmult(q67, q78) # left_tarsus --> left_toe_roll
print('left_tarsus --> left_toe_roll: ', q68) # Werte korrekt

print()

q04 = qmt.qmult(q02, q24)
#print(q04)# wahrschienlich richtig ist alles negiert

q04 = qmt.qmult(qmt.qmult(q01, q12), qmt.qmult(q23, q34))
#print(q04)# wahrschienlich richtig ist alles negiert

q03 = qmt.qmult(qmt.qmult(q01, q12), q23)
#print(q03) # negiert aber korrekt

q04 = qmt.qmult(qmt.qmult(qmt.qmult(q01, q12), q23), q34)
#print(q04)# negiert aber korrekt

q05 = qmt.qmult(qmt.qmult(qmt.qmult(qmt.qmult(q01, q12), q23), q34), q45)
#print(q05) # negiert aber korrekt

q06 = qmt.qmult(qmt.qmult(qmt.qmult(qmt.qmult(qmt.qmult(q01, q12), q23), q34), q45), q56)
#print(q06) # negiert aber korrekt

q07 = qmt.qmult(qmt.qmult(qmt.qmult(qmt.qmult(qmt.qmult(qmt.qmult(q01, q12), q23), q34), q45), q56), q67)
#print(q07) # negiert aber korrekt

q08 = qmt.qmult(qmt.qmult(qmt.qmult(qmt.qmult(qmt.qmult(qmt.qmult(qmt.qmult(q01, q12), q23), q34), q45), q56), q67), q78)
print(q08)# ab hier ist es falsch, wild weil unten veim vorherigen war es mit 8 richtig



q35 = qmt.qmult(q34, q45) # left_hip_pitch --> left shin
#print('left_hip_pitch --> left_shin:     ', q35) # Werte korrekt :)

q57 = qmt.qmult(q56, q67) # left_shin --> left toe_pitch
#print('left_shin --> left_tarsus:        ', q57) # 

q36 = qmt.qmult(q35, q46) # left_hip_pitch --> left_tarsus
#print('left_hip_pitch --> left_tarsus:   ', q36) # Werte korrekt :)
q36 = qmt.qmult(q35, q56) # left_hip_pitch --> left_tarsus
#print('left_hip_pitch --> left_tarsus:   ', q36, " test") # Werte korrekt :)


q36 = qmt.qmult(qmt.qmult(q34, q45), qmt.qmult(q45, q56))
#print(q36) # Werte korrekt






q68 = qmt.qmult(q67, q78) # left_tarsus --> left_toe_roll
#print('left_tarsus --> left_toe_roll:    ', q68) # Werte korrekt :)


q38 =qmt.qmult(q36, q68) # left_hip_pitch --> left_toe_roll
#print('left_hip_pitch --> left_toe_roll: ',q38) # Werte korrekt

q79 = qmt.qmult(q78, q89) # left_toe_pitch --> left_toe 
#print('left_toe_pitch --> left_toe:      ', q79) # Werte korrekt :)



q03 = qmt.qmult(q02, q23_fake)
q04 = qmt.qmult(q03, q34)

#print(q04)

q69 = qmt.qmult(q68, q89)
#print(q69) # irgeendwa ist falsch aber waaas


w x y z
torso --> left_hip_yaw:            [ 1.11022302e-16 -1.38777878e-17 -9.82450397e-01 -1.86524041e-01]
left_hip_yaw --> left_knee:        [ 0.65328111  0.65328111 -0.27059774  0.27059774]
left_knee --> left_tarsus:         [0.62251465 0.         0.         0.78260815]
left_tarsus --> left_toe_roll:  [ 0.25912296 -0.65791739  0.25912296  0.65791739]

[-0.70597103 -0.04005306  0.22147318 -0.67152734]
