In [2]:
import os
import mujoco_viewer
import mujoco._render
import numpy as np
import qmt

In [3]:
model = mujoco.MjModel.from_xml_path('/home/martin/Bachelorarbeit/DIGIT/digit-v3_stl/digit-v3.xml') # create the Model from Path
data = mujoco.MjData(model) # creates the data

In [ ]:
viewer = mujoco_viewer.MujocoViewer(model, data)

# simulate and render
for _ in range(10000):
    if viewer.is_alive:
        
        
        # control motor
        data.ctrl[0] = 500 * (np.deg2rad(10.0) - data.sensordata[model.sensor_adr[mujoco.mj_name2id(model, 19, "left-hip-roll" )]])
        data.ctrl[6] = 500 * (np.deg2rad(0.0) - data.sensordata[model.sensor_adr[mujoco.mj_name2id(model, 19, "right-hip-roll" )]]) # in der simulation 1/80 torque drauf geben, gear ratio

        #print(data.sensordata[model.sensor_adr[mujoco.mj_name2id(model, 19, "left-hip-roll")]])
        #print('vel: ', data.sensordata[model.sensor_adr[mujoco.mj_name2id(model, 19, "left-hip-roll-vel")]])

        mujoco.mj_step(model, data)
        viewer.render()
    else:
        break

# close
viewer.close()

Pressed ESC
Quitting.


In [ ]:
#print(mujoco.mj_name2id(model, 19, "left-hip-roll" )) # die Nummer 19 sind die Sensoren
#print(mujoco.mj_name2id(model, 18, "left-hip-roll")) # Nummer 18 sind die Motoren

#print(mujoco.mj_name2id(model, 19, "base-pos"))
print(data.sensordata[model.sensor_adr[mujoco.mj_name2id(model, 19, "base-pos")]:3]) #  x y z # also hierrüber bekomme  xyz bei meine Pelvis-Pose
print(data.sensordata[model.sensor_adr[mujoco.mj_name2id(model, 19, "base-quat")]:model.sensor_adr[mujoco.mj_name2id(model, 19, "base-quat")] + 4])
print(qmt.eulerAngles(data.sensordata[model.sensor_adr[mujoco.mj_name2id(model, 19, "base-quat")]:model.sensor_adr[mujoco.mj_name2id(model, 19, "base-quat")] + 4])) # qmt ist wxyz #  euler sind zyx

#qmt.eulerAngles(base_quat)

[0.36819057 0.27885422 1.506454  ]
[0.69354141 0.0713504  0.54035533 0.47108975]
[1.60885731 0.75089413 0.98226635]


In [5]:
# Durchlaufe alle Gelenke im Modell
for joint_id in range(model.nsensor):  # model.nsensor ist die Number of Sensor;  model.njnt ist die Number of Joints
    # Holen Sie den Namen des Gelenks mit der aktuellen ID
    joint_name = mujoco.mj_id2name(model, 19, joint_id)
    
    # Zeige die ID und den Namen des Gelenks an
    print(f"ID: {joint_id}, Name: {joint_name}")

ID: 0, Name: base-pos
ID: 1, Name: base-quat
ID: 2, Name: left-hip-roll
ID: 3, Name: left-hip-yaw
ID: 4, Name: left-hip-pitch
ID: 5, Name: left-knee
ID: 6, Name: left-shin
ID: 7, Name: left-tarsus
ID: 8, Name: left-toe-A
ID: 9, Name: left-toe-B
ID: 10, Name: left-toe-pitch
ID: 11, Name: left-toe-roll
ID: 12, Name: right-hip-roll
ID: 13, Name: right-hip-yaw
ID: 14, Name: right-hip-pitch
ID: 15, Name: right-knee
ID: 16, Name: right-shin
ID: 17, Name: right-tarsus
ID: 18, Name: right-toe-A
ID: 19, Name: right-toe-B
ID: 20, Name: right-toe-pitch
ID: 21, Name: right-toe-roll
ID: 22, Name: left-shoulder-roll
ID: 23, Name: left-shoulder-pitch
ID: 24, Name: left-shoulder-yaw
ID: 25, Name: left-elbow
ID: 26, Name: right-shoulder-roll
ID: 27, Name: right-shoulder-pitch
ID: 28, Name: right-shoulder-yaw
ID: 29, Name: right-elbow
ID: 30, Name: base-angvel
ID: 31, Name: base-linvel
ID: 32, Name: left-hip-roll-vel
ID: 33, Name: left-hip-yaw-vel
ID: 34, Name: left-hip-pitch-vel
ID: 35, Name: left-knee

In [6]:
for i in range(model.njnt):
    # Name des Gelenks
    joint_name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_JOINT, i)
    
    # Startindex von qpos für dieses Gelenk
    qpos_addr = model.jnt_qposadr[i]
    
    print(f"Joint name: {joint_name}, qpos index: {qpos_addr}")

Joint name: None, qpos index: 0
Joint name: left-hip-roll, qpos index: 7
Joint name: left-hip-yaw, qpos index: 8
Joint name: left-hip-pitch, qpos index: 9
Joint name: left-achillies-rod, qpos index: 10
Joint name: left-knee, qpos index: 14
Joint name: left-shin, qpos index: 15
Joint name: left-tarsus, qpos index: 16
Joint name: left-heel-spring, qpos index: 17
Joint name: left-toe-A, qpos index: 18
Joint name: left-toe-A-rod, qpos index: 19
Joint name: left-toe-B, qpos index: 23
Joint name: left-toe-B-rod, qpos index: 24
Joint name: left-toe-pitch, qpos index: 28
Joint name: left-toe-roll, qpos index: 29
Joint name: left-shoulder-roll, qpos index: 30
Joint name: left-shoulder-pitch, qpos index: 31
Joint name: left-shoulder-yaw, qpos index: 32
Joint name: left-elbow, qpos index: 33
Joint name: right-hip-roll, qpos index: 34
Joint name: right-hip-yaw, qpos index: 35
Joint name: right-hip-pitch, qpos index: 36
Joint name: right-achillies-rod, qpos index: 37
Joint name: right-knee, qpos in

In [ ]:
model.sensor_adr[mujoco.mj_name2id(model, 19, "left-hip-roll" )] # es ist die 7 das base-pos 3stk sind und base-quat 4stk. also 0-6; left-hip-roll ist dann 7

7

In [ ]:
print(data.sensordata[model.sensor_adr[mujoco.mj_name2id(model, 19, "left-hip-roll" )]])

0.42712474150216717


In [ ]:
'''
base-quat ist w x y z und euler macht daraus z y x
'''


[ 1.99999999e+00  9.99999987e-01 -1.05787118e-08]
[ 0.47415988 -0.40342268  0.25903472  0.73846027]


array([ 0.47415988, -0.40342268,  0.25903472,  0.73846026])